BLT-122 Ansible playbooks for deploying MongoDB and Grafana on GCP instances
BlueTeam2/awx-ansible pull request #6
Opened 2023-12-08 13:38 UTC by AndriyGalias

Added Ansible playbooks mongo.yml and grafana.yml with dynamic inventory

2023-12-08 15:10 UTC, arkma requested changes

2023-12-08 15:10 UTC, arkma commented on my-ansible-playbooks/ansible.cfg
You should probably add ansible config to gitignore in order to possible conflicts with AWX

2023-12-08 15:10 UTC, arkma commented on my-ansible-playbooks/group_vars/all.yml
It would better to move specific server configuration to group vars

2023-12-08 15:10 UTC, arkma commented on my-ansible-playbooks/inventory_gcp.yml
Try to create keyed groups by labels and use them in your playbooks

2023-12-09 15:06 UTC, arkma approved these changes

2023-12-09 15:06 UTC, arkma commented on my-ansible-playbooks/mongo.yml
> +        line: "deb [ arch=amd64,arm64 signed-by={{ mongo_user_keyrings_dir }}-{{ mongo_version }}.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/{{ mongo_version }} multiverse"
You can move this long value to the variable for better readability.

2023-12-09 19:16 UTC, sbodia approved these changes

2023-12-11 08:26 UTC, merged