Nexus playbook
BlueTeam2/awx-ansible pull request #8
Opened 2023-12-12 15:03 UTC by Legamanchik

Playbook for install nexus but you need to update packages first

2023-12-12 15:13 UTC, arkma requested changes
Where is your inventory file? Do you use GCP dynamic inventory?
How can I verify that this ansible playbook installs nexus correctly?

2023-12-12 15:13 UTC, arkma commented on nexus.yml
> +  hosts: your_gcp_vm_group
You may forgot to specify inventory group. It would better to use `server_nexus` group.

2023-12-12 15:13 UTC, arkma commented on nexus.yml
> +        password: "s3cr3t"
Move credentials to environment variable to be able to inject them via AWX

2023-12-12 15:13 UTC, arkma commented on nexus.yml
> +    - { role: ansible-thoteam.nexus3-oss, tags: ['ansible-thoteam.nexus3-oss'] }
I don't see this role in the `ansible-galaxy`. Where can we get this role?

2023-12-16 14:00 UTC, arkma approved these changes

2023-12-16 14:01 UTC, sbodia approved these changes

2023-12-16 14:01 UTC, merged